/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSiteIdRouteImport } from './routes/app/$siteId'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as WPublicIdRouteImport } from './routes/w.$publicId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSiteIdIndexRouteImport } from './routes/app/$siteId.index'
import { Route as AppSiteIdConversationsRouteImport } from './routes/app/$siteId.conversations'
import { Route as AppSiteIdEmailRouteImport } from './routes/app/$siteId.email'
import { Route as AppSiteIdInsightsRouteImport } from './routes/app/$siteId.insights'
import { Route as AppSiteIdInstallRouteImport } from './routes/app/$siteId.install'
import { Route as AppSiteIdKnowledgeRouteImport } from './routes/app/$siteId.knowledge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteIdRoute = AppSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const WPublicIdRoute = WPublicIdRouteImport.update({
  id: '/w/$publicId',
  path: '/w/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSiteIdIndexRoute = AppSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSiteIdRoute,
} as any)
const AppSiteIdConversationsRoute = AppSiteIdConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppSiteIdRoute,
} as any)
const AppSiteIdEmailRoute = AppSiteIdEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppSiteIdRoute,
} as any)
const AppSiteIdInsightsRoute = AppSiteIdInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppSiteIdRoute,
} as any)
const AppSiteIdInstallRoute = AppSiteIdInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => AppSiteIdRoute,
} as any)
const AppSiteIdKnowledgeRoute = AppSiteIdKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppSiteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/$siteId': typeof AppSiteIdRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/w/$publicId': typeof WPublicIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$siteId/conversations': typeof AppSiteIdConversationsRoute
  '/app/$siteId/email': typeof AppSiteIdEmailRoute
  '/app/$siteId/insights': typeof AppSiteIdInsightsRoute
  '/app/$siteId/install': typeof AppSiteIdInstallRoute
  '/app/$siteId/knowledge': typeof AppSiteIdKnowledgeRoute
  '/app/$siteId/': typeof AppSiteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/settings': typeof AppSettingsRoute
  '/w/$publicId': typeof WPublicIdRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$siteId/conversations': typeof AppSiteIdConversationsRoute
  '/app/$siteId/email': typeof AppSiteIdEmailRoute
  '/app/$siteId/insights': typeof AppSiteIdInsightsRoute
  '/app/$siteId/install': typeof AppSiteIdInstallRoute
  '/app/$siteId/knowledge': typeof AppSiteIdKnowledgeRoute
  '/app/$siteId': typeof AppSiteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/$siteId': typeof AppSiteIdRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/w/$publicId': typeof WPublicIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$siteId/conversations': typeof AppSiteIdConversationsRoute
  '/app/$siteId/email': typeof AppSiteIdEmailRoute
  '/app/$siteId/insights': typeof AppSiteIdInsightsRoute
  '/app/$siteId/install': typeof AppSiteIdInstallRoute
  '/app/$siteId/knowledge': typeof AppSiteIdKnowledgeRoute
  '/app/$siteId/': typeof AppSiteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/pricing'
    | '/app/$siteId'
    | '/app/settings'
    | '/w/$publicId'
    | '/app/'
    | '/api/auth/$'
    | '/app/$siteId/conversations'
    | '/app/$siteId/email'
    | '/app/$siteId/insights'
    | '/app/$siteId/install'
    | '/app/$siteId/knowledge'
    | '/app/$siteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/pricing'
    | '/app/settings'
    | '/w/$publicId'
    | '/app'
    | '/api/auth/$'
    | '/app/$siteId/conversations'
    | '/app/$siteId/email'
    | '/app/$siteId/insights'
    | '/app/$siteId/install'
    | '/app/$siteId/knowledge'
    | '/app/$siteId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/login'
    | '/pricing'
    | '/app/$siteId'
    | '/app/settings'
    | '/w/$publicId'
    | '/app/'
    | '/api/auth/$'
    | '/app/$siteId/conversations'
    | '/app/$siteId/email'
    | '/app/$siteId/insights'
    | '/app/$siteId/install'
    | '/app/$siteId/knowledge'
    | '/app/$siteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  WPublicIdRoute: typeof WPublicIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$siteId': {
      id: '/app/$siteId'
      path: '/$siteId'
      fullPath: '/app/$siteId'
      preLoaderRoute: typeof AppSiteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/w/$publicId': {
      id: '/w/$publicId'
      path: '/w/$publicId'
      fullPath: '/w/$publicId'
      preLoaderRoute: typeof WPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$siteId/': {
      id: '/app/$siteId/'
      path: '/'
      fullPath: '/app/$siteId/'
      preLoaderRoute: typeof AppSiteIdIndexRouteImport
      parentRoute: typeof AppSiteIdRoute
    }
    '/app/$siteId/conversations': {
      id: '/app/$siteId/conversations'
      path: '/conversations'
      fullPath: '/app/$siteId/conversations'
      preLoaderRoute: typeof AppSiteIdConversationsRouteImport
      parentRoute: typeof AppSiteIdRoute
    }
    '/app/$siteId/email': {
      id: '/app/$siteId/email'
      path: '/email'
      fullPath: '/app/$siteId/email'
      preLoaderRoute: typeof AppSiteIdEmailRouteImport
      parentRoute: typeof AppSiteIdRoute
    }
    '/app/$siteId/insights': {
      id: '/app/$siteId/insights'
      path: '/insights'
      fullPath: '/app/$siteId/insights'
      preLoaderRoute: typeof AppSiteIdInsightsRouteImport
      parentRoute: typeof AppSiteIdRoute
    }
    '/app/$siteId/install': {
      id: '/app/$siteId/install'
      path: '/install'
      fullPath: '/app/$siteId/install'
      preLoaderRoute: typeof AppSiteIdInstallRouteImport
      parentRoute: typeof AppSiteIdRoute
    }
    '/app/$siteId/knowledge': {
      id: '/app/$siteId/knowledge'
      path: '/knowledge'
      fullPath: '/app/$siteId/knowledge'
      preLoaderRoute: typeof AppSiteIdKnowledgeRouteImport
      parentRoute: typeof AppSiteIdRoute
    }
  }
}

interface AppSiteIdRouteChildren {
  AppSiteIdConversationsRoute: typeof AppSiteIdConversationsRoute
  AppSiteIdEmailRoute: typeof AppSiteIdEmailRoute
  AppSiteIdInsightsRoute: typeof AppSiteIdInsightsRoute
  AppSiteIdInstallRoute: typeof AppSiteIdInstallRoute
  AppSiteIdKnowledgeRoute: typeof AppSiteIdKnowledgeRoute
  AppSiteIdIndexRoute: typeof AppSiteIdIndexRoute
}

const AppSiteIdRouteChildren: AppSiteIdRouteChildren = {
  AppSiteIdConversationsRoute: AppSiteIdConversationsRoute,
  AppSiteIdEmailRoute: AppSiteIdEmailRoute,
  AppSiteIdInsightsRoute: AppSiteIdInsightsRoute,
  AppSiteIdInstallRoute: AppSiteIdInstallRoute,
  AppSiteIdKnowledgeRoute: AppSiteIdKnowledgeRoute,
  AppSiteIdIndexRoute: AppSiteIdIndexRoute,
}

const AppSiteIdRouteWithChildren = AppSiteIdRoute._addFileChildren(
  AppSiteIdRouteChildren,
)

interface AppRouteChildren {
  AppSiteIdRoute: typeof AppSiteIdRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSiteIdRoute: AppSiteIdRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  WPublicIdRoute: WPublicIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
